const fs = require('fs');

const filePath = 'c:/Users/acer/OneDrive/Desktop/Any-Khata/any-khata-app/constants/i18n.ts';
let content = fs.readFileSync(filePath, 'utf-8');

// Update Locale
content = content.replace("export type Locale = 'en' | 'gu';", "export type Locale = 'en' | 'gu' | 'hi';");

// Hindi dictionary
const hi_dict = `  hi: {
    // Common
    'common.cancel': 'रद्द करें',
    'common.continue': 'जारी रखें',
    'common.ok': 'ठीक है',
    'common.back': 'पीछे',
    'common.go_back': 'पीछे जाएं',
    'common.save': 'सहेजें',
    'common.save_changes': 'परिवर्तन सहेजें',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.app_name': 'Any Khata',
    'common.days': 'दिन',
    'common.try_again': 'पुनः प्रयास करें',
    'common.something_went_wrong': 'कुछ गलत हो गया',
    'common.please_try_again': 'कृपया पुनः प्रयास करें।',
    'common.permission_required': 'अनुमति आवश्यक',
    'common.permission_denied_msg': 'कृपया अपनी फोटो लाइब्रेरी तक पहुंच की अनुमति दें।',
    'common.placeholder_business': 'जैसे, शर्मा ग्रोसरी',
    'common.placeholder_owner': 'जैसे, रमेश शर्मा',
    'common.placeholder_phone': '10-अंकों का मोबाइल नंबर',
    'common.emoji_notebook': '📒',
    'common.check_mark': '✓',

    // Login
    'login.tagline': 'आपका हिसाब, डिजिटल सुरक्षा',
    'login.feature_track': 'ग्राहक के बकाया को ट्रैक करें',
    'login.feature_daily': 'दैनिक अपरिवर्तनीय रिकॉर्ड',
    'login.feature_realtime': 'रीयल-टाइम ग्राहक दृश्य',
    'login.google_btn': 'Google के साथ जारी रखें',
    'login.footer': 'ग्राहकों के लिए मुफ्त • व्यवसायों के लिए ₹11/माह',

    // Profile
    'profile.title': 'प्रोफ़ाइल',
    'profile.settings.notifications': 'सूचनाएं',
    'profile.settings.language': 'भाषा',
    'profile.settings.help_support': 'सहायता और समर्थन',
    'profile.settings.privacy_policy': 'गोपनीयता नीति',
    'profile.settings.terms_of_service': 'सेवा की शर्तें',
    'profile.delete_account': 'खाता हटाएं',
    'profile.delete_confirm': 'क्या आप वाकई अपना खाता हटाना चाहते हैं?',
    'profile.delete_error': 'खाता हटाने में विफल। कृपया पुनः प्रयास करें।',
    'profile.delete_undo_msg': 'इसे पूर्ववत नहीं किया जा सकता।',
    'profile.support_email_msg': 'समर्थन के लिए, हमें support@anykhata.in पर ईमेल करें',
    'profile.payment_success': 'भुगतान सफल! अब आप अपना व्यवसाय पंजीकृत कर सकते हैं।',
    'profile.payment_failed': 'भुगतान संसाधित नहीं किया जा सका। कृपया पुनः प्रयास करें।',
    'profile.subscription_ended_msg': 'सदस्यता समाप्त — जारी रखने के लिए नवीनीकृत करें',
    'profile.pay_reactivate_btn': 'पुनः सक्रिय करने के लिए ₹11/माह का भुगतान करें',
    'profile.expires_in': 'समाप्त होगा',
    'profile.sign_out': 'साइन आउट',
    'profile.my_business': 'मेरा व्यवसाय',
    'profile.register_business': 'व्यवसाय पंजीकृत करें',
    'profile.setup_profile_desc': 'शुरू करने के लिए अपना व्यवसाय प्रोफ़ाइल सेट करें',
    'profile.start_khata': 'अपना खाता शुरू करें',
    'profile.manage_customers': 'अपने सभी ग्राहकों का प्रबंधन करें',
    'profile.advertise_business': 'अपने व्यवसाय का विज्ञापन दें',
    'profile.active_plan_11': '₹11 योजना सक्रिय',
    'profile.active_plan_100': '₹100 विज्ञापन सक्रिय',
    'profile.renew_ad_btn': '₹100/माह के लिए नवीनीकृत करें',
    'profile.reach_local_msg': 'विज्ञापन पृष्ठ पर स्थानीय ग्राहकों तक पहुंचें',
    'profile.pay_plan_11': '₹11/माह का भुगतान करें',
    'profile.pay_ad_btn': '₹100/माह का भुगतान करें',
    'profile.select_language': 'भाषा चुनें',
    'profile.expired': 'समाप्त',

    // Home
    'home.filter.all': 'सभी ग्राहक',
    'home.filter.pending': 'बकाया शेष',
    'home.filter.name': 'नाम से',
    'home.filter.recent': 'हाल के',
    'home.total_outstanding': 'कुल बकाया',
    'home.active_customers': 'सक्रिय ग्राहक',
    'home.linked_shops': 'जुड़ी दुकानें',
    'home.business_customers': 'व्यापार ग्राहक',
    'home.your_khatas': 'आपके खाते',
    'home.add_customer_title': 'ग्राहक जोड़ें',
    'home.search_placeholder': 'ग्राहक का नाम या फोन खोजें...',
    'home.greeting': 'जय श्री कृष्ण,',
    'home.tagline': 'आपका डिजिटल लेजर',
    'home.refreshing': 'आपका लेजर ताज़ा हो रहा है...',
    'home.load_failed': 'हिसाब लोड नहीं हुआ',
    'home.no_customers': 'कोई ग्राहक नहीं मिला',
    'home.add_first_customer': 'शुरू करने के लिए अपना पहला ग्राहक जोड़ें',
    'home.link_code': 'लिंक कोड:',
    'home.customer_added': 'ग्राहक जुड़ गया!',
    'home.error_name_required': 'नाम आवश्यक है',
    'home.error_phone_length': 'फोन 10 अंकों का होना चाहिए',
    'home.error_phone_digits': 'केवल अंक होने चाहिए',
    'home.auth_error': 'उपयोगकर्ता प्रमाणित नहीं है।',
    'home.business_not_found': 'आपका व्यवसाय नहीं मिला। कृपया सुनिश्चित करें कि आपने व्यवसाय पंजीकृत किया है।',
    'home.active_records_msg': 'आपके खाते में सक्रिय रिकॉर्ड',
    'home.across': 'भर में',
    'home.linked_khatas': 'जुड़े खाते',
    'home.add_customer_failed': 'ग्राहक जोड़ने में विफल',
    'home.delete_customer_failed': 'ग्राहक हटाने में विफल',
    'home.share_code_msg': 'यह कोड उनके साथ साझा करें:',
    'home.share_code_btn': 'कोड साझा करें',
    'home.customers': 'ग्राहक',
    'home.given': 'दिया',
    'home.got': 'मिला',
    'My Khata': 'मेरा खाता',
    'Balance': 'बकाया',

    // My Khata (Customer View)
    'my_khata.empty_msg': 'दिखाने के लिए कोई खाता नहीं',
    'my_khata.empty_desc': 'एक बार जब कोई व्यवसाय आपको आपके फोन नंबर के साथ जोड़ता है, तो आपका खाता यहां दिखाई देगा।',
    'my_khata.added_by': 'द्वारा जोड़ा गया: ',
    'my_khata.you_owe': 'आपको देना है: ',

    // Dashboard
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.no_business_found': 'कोई व्यवसाय नहीं मिला',
    'dashboard.good_morning': 'सुप्रभात, ',
    'dashboard.morning_coffee': '! ☕',
    'dashboard.renew_desc': 'आपकी सदस्यता समाप्त हो गई है। एंट्री जोड़ना जारी रखने के लिए नवीनीकृत करें।',
    'dashboard.renew_now': 'अभी नवीनीकृत करें',
    'dashboard.today': 'आज',
    'dashboard.month': 'महीना',
    'dashboard.customers': 'ग्राहक',
    'dashboard.pending': 'बकाया',
    'dashboard.recent_customers': 'हाल के ग्राहक',
    'dashboard.see_all': 'सभी देखें →',
    'dashboard.no_customers': 'अभी कोई ग्राहक नहीं',
    'dashboard.add_customer_desc': 'ट्रैकिंग शुरू करने के लिए अपना पहला ग्राहक जोड़ें',
    'dashboard.add_customer_btn': '+ ग्राहक जोड़ें',

    // Ads
    'ads.title': 'विज्ञापन और ऑफ़र',
    'ads.empty': 'अभी कोई विज्ञापन नहीं। विज्ञापन देने वाले पहले बनें!',
    'ads.featured_businesses': 'विशेष व्यवसाय',
    'ads.whatsapp': 'व्हाट्सएप',
    'ads.website': 'वेबसाइट',
    'ads.location': 'स्थान',
    'ads.view_on_maps': 'नक्शे पर देखें',
    'ads.gstin': 'जीएसटीआईएन (GSTIN)',
    'ads.loading_offers': 'ऑफ़र लोड हो रहे हैं...',
    'ads.no_featured': 'अभी कोई विशेष व्यवसाय नहीं',
    'ads.first_ad_btn': 'विज्ञापन देने वाले पहले बनें',

    // Ad Submit & Edit
    'ad_submit.title': 'विज्ञापन दें',
    'ad_submit.subtitle': 'अपने व्यवसाय का प्रचार करें',
    'ad_submit.business_details': 'व्यवसाय विवरण',
    'ad_submit.store_photo': 'स्टोर की फोटो',
    'ad_submit.tap_to_upload': 'स्टोर की फोटो अपलोड करने के लिए टैप करें',
    'ad_submit.business_name': 'व्यवसाय का नाम',
    'ad_submit.owner_name': 'मालिक का नाम',
    'ad_submit.whatsapp_number': 'व्हाट्सएप नंबर',
    'ad_submit.whatsapp_hint': 'ग्राहक आपको व्हाट्सएप करने के लिए टैप करेंगे',
    'ad_submit.gstin_number': 'जीएसटीआईएन नंबर',
    'ad_submit.gstin_placeholder': 'जैसे, 22AAAAA0000A1Z5',
    'ad_submit.website_url': 'वेबसाइट URL',
    'ad_submit.maps_url': 'Google Maps URL',
    'ad_submit.optional_details': 'वैकल्पिक विवरण',
    'ad_submit.optional_hint': 'जो लागू हों उन्हें भरें — वे आपके व्यवसाय कार्ड में दिखाई देंगे।',
    'ad_submit.pay_go_live': '₹100 का भुगतान करें और लाइव हों',
    'ad_submit.error_business_name': 'व्यवसाय का नाम कम से कम 2 अक्षरों का होना चाहिए',
    'ad_submit.error_owner_name': 'मालिक का नाम कम से कम 2 अक्षरों का होना चाहिए',
    'ad_submit.error_phone_valid': 'एक वैध 10-अंकों का मोबाइल नंबर दर्ज करें',
    'ad_submit.error_gstin_max': 'GSTIN अधिकतम 15 अक्षरों का होना चाहिए',
    'ad_submit.error_website_https': 'वेबसाइट URL https:// से शुरू होना चाहिए',
    'ad_submit.error_maps_start': 'नक्शे का URL https://maps.app.goo.gl/ या https://maps.google.com/ से शुरू होना चाहिए',
    'ad_submit.upload_store_photo_msg': 'कृपया स्टोर की फोटो अपलोड करें',
    'ad_submit.success_title': 'सफलता! 🎉',
    'ad_submit.success_msg': 'आपका विज्ञापन अब लाइव है!',
    'ad_edit.title': 'अपना विज्ञापन संपादित करें',
    'ad_edit.subtitle': 'अपने सक्रिय विज्ञापन का विवरण अपडेट करें।',
    'ad_edit.success_msg': 'विज्ञापन अपडेट किया गया!',

    // Components & Others
    'guard.subscription_required': 'सदस्यता आवश्यक',
    'guard.desc': 'Any Khata पर अपने व्यवसाय को सक्रिय करने के लिए ₹11/माह का भुगतान करें।',
    'guard.activate_btn': '₹11 के लिए सक्रिय करें',
    'daylog.add_entry': 'एंट्री जोड़ें',
    'daylog.past_locked': 'पिछली एंट्री लॉक हैं',
    'daylog.live': 'लाइव',
    'daylog.note': 'नोट',
    'customer_card.due': 'बकाया',
    'customer_card.paid': 'भुगतान किया',
    'balance.total_billed': 'कुल बिल',
    'balance.paid': 'भुगतान किया',
    'balance.remaining': 'शेष',

    // Customer Management
    'Add Customer': 'ग्राहक जोड़ें',
    'Customer Name': 'ग्राहक का नाम',
    'Customer Phone': 'ग्राहक का फोन',
    'Customer added!': 'ग्राहक जुड़ गया!',
    'Share this code with them:': 'यह कोड उनके साथ साझा करें:',
    'Share Code': 'कोड साझा करें',
    'Remove Customer': 'ग्राहक निकालें',

    // Common Actions
    'Cancel': 'रद्द करें',
    'Save': 'सहेजें',
    'OK': 'ठीक है',
    'Link': 'लिंक करें',

    // Entry & Payment
    'Add Entry': 'एंट्री जोड़ें',
    'Add Entry for': 'के लिए एंट्री जोड़ें',
    'Record Payment': 'भुगतान दर्ज करें',
    'Enter the amount received from customer.': 'ग्राहक से प्राप्त राशि दर्ज करें।',
    'Amount (₹)': 'राशि (₹)',
    'Note (Optional)': 'नोट (वैकल्पिक)',
    'e.g. Received via GPay': 'जैसे GPay के माध्यम से प्राप्त',
    'Save Entry': 'एंट्री सहेजें',
    'AMOUNT TO RECORD': 'दर्ज करने के लिए राशि',
    'e.g., 6 cups chai': 'जैसे, 6 कप चाय',
    'Gave (Credit)': 'दिया (उधार)',
    'Got (Payment)': 'मिला (भुगतान)',
    'Day Total:': 'दिन का कुल:',

    // Khata / Ledger
    'My Khatas': 'मेरे खाते',
    'Your Khatas': 'आपके खाते',
    'View All': 'सभी देखें',
    'Check your khatas': 'अपने खाते जांचें',
    'Go to Khata tab to see linked shops': 'जुड़ी दुकानें देखने के लिए खाता टैब पर जाएं',
    'Go to Khata Tab': 'खाता टैब पर जाएं',
    'Your Linked Shops': 'आपकी जुड़ी दुकानें',
    'Manage your credit and payments across all local shops': 'सभी स्थानीय दुकानों में अपना उधार और भुगतान प्रबंधित करें',
    'No Linked Khatas': 'कोई जुड़ा खाता नहीं',
    'Link a shop using their 6-digit code to see your balance and history.': 'अपना शेष और इतिहास देखने के लिए उनके 6-अंकीय कोड का उपयोग करके दुकान को लिंक करें।',
    'Link a Khata Now': 'अभी खाता लिंक करें',
    'Link a Khata': 'खाता लिंक करें',
    'Enter the 6-digit shop code provided by the business owner to sync your ledger.': 'अपना लेजर सिंक करने के लिए व्यवसाय स्वामी द्वारा प्रदान किया गया 6-अंकीय दुकान कोड दर्ज करें।',
    'Shop Code': 'दुकान कोड',
    'Link Shop': 'दुकान लिंक करें',
    'Shop Ledger': 'दुकान का लेजर',
    'View Details': 'विवरण देखें',
    'Fetching your records...': 'आपके रिकॉर्ड लाए जा रहे हैं...',

    // Ledger Screen
    'View Only': 'केवल देखें',
    'Total Net Balance': 'कुल शुद्ध शेष',
    'No entries yet': 'अभी कोई एंट्री नहीं',

    // Missing Simple UI Keys
    'Version 1.0.42': 'संस्करण 1.0.42',
    'Expires in': 'समाप्त होगा',
    'days': 'दिन',
    'Edit Business Details': 'व्यवसाय विवरण संपादित करें',
    'Business Name': 'व्यवसाय का नाम',
    'e.g., Ramesh Tea Stall': 'जैसे, रमेश टी स्टॉल',
    'Owner Name': 'मालिक का नाम',
    'e.g., Ramesh Kumar': 'जैसे, रमेश कुमार',
    'Phone Number': 'फोन नंबर',
    '10-digit mobile number': '10-अंकों का मोबाइल नंबर',
    'Notifications': 'सूचनाएं',
    'Push Notifications': 'पुश सूचनाएं',
    'Notification Types': 'सूचना प्रकार',
    'Privacy Policy': 'गोपनीयता नीति',
    'Terms of Service': 'सेवा की शर्तें',
    'Contact Us': 'हमसे संपर्क करें',
    'Add Item': 'आइटम जोड़ें',
    'Edit Entry': 'एंट्री संपादित करें',
    'Update the transaction details.': 'लेनदेन विवरण अपडेट करें।',

    'home.recent_customers': 'हाल के ग्राहक',

    'GAVE': 'दिया',
    'GOT': 'मिला',
    'Day Net': 'दिन कुल',

    'Record what the customer purchased today.': 'आज ग्राहक ने क्या खरीदा वह दर्ज करें।',
    'Description': 'विवरण',
    'e.g., 6 cups tea, Parle G packet': 'जैसे, 6 कप चाय, Parle G पैकेट',
    'Quantity (Optional)': 'मात्रा (वैकल्पिक)',
    'e.g., 6': 'जैसे, 6',
    'e.g., 30': 'जैसे, 30',
    'Enter the amount received from the customer.': 'ग्राहक से मिली राशि दर्ज करें।',
    'e.g., 500': 'जैसे, 500',
    'e.g., Partial payment, Full settlement': 'जैसे, आंशिक भुगतान, पूर्ण निपटान',

    'linked shops': 'जुड़ी दुकानें',
    'Manage your credit and payments across all local shops.': 'सभी स्थानीय दुकानों में अपना उधार और भुगतान प्रबंधित करें।',

    'Share Statement': 'विवरण साझा करें',
    'New Entry': 'नई एंट्री',
    'AMOUNT': 'राशि',
    'What is this for? (e.g. 2kg Sugar)': 'यह किसलिए है? (जैसे 2 किलो चीनी)',
    'Save Transaction': 'लेनदेन सहेजें',
    'e.g. 123456': 'जैसे 123456',

    'Discover local businesses': 'स्थानीय व्यवसाय खोजें',

    'Business Account': 'व्यवसाय खाता',
    'Advertisements': 'विज्ञापन',
    'Preferences': 'प्राथमिकताएं',

    'Change Photo': 'फ़ोटो बदलें',

    'Notifications are enabled': 'सूचनाएं सक्षम हैं',
    'When a new transaction is added to your khata': 'जब आपकी खाता में नया लेनदेन जोड़ा जाए',
    'Payment Received': 'भुगतान प्राप्त हुआ',
    'When a customer makes a payment': 'जब ग्राहक भुगतान करे',
    'Balance Reminders': 'बकाया रिमाइंडर',
    'Periodic reminders for outstanding balances': 'बकाया राशि के लिए नियमित रिमाइंडर',
    'App Updates': 'ऐप अपडेट',
    'News about new features and improvements': 'नई सुविधाओं और सुधारों की खबर',
    'Notification preferences are saved locally on this device. To manage system-level notification permissions, go to your device Settings → Any Khata → Notifications.': 'सूचना प्राथमिकताएं इस डिवाइस पर स्थानीय रूप से सहेजी जाती हैं। सिस्टम-स्तर की सूचना अनुमतियां प्रबंधित करने के लिए, डिवाइस सेटिंग्स → Any Khata → सूचनाएं पर जाएं।',
  }`;

if (content.includes("  gu: {")) {
    content = content.replace("  }\\n} as const;", "  },\\n" + hi_dict + "\\n} as const;");
    // Also try the exact string to be safe if newline is not \n literally
    content = content.replace("  }\n} as const;", "  },\n" + hi_dict + "\n} as const;");
}

fs.writeFileSync(filePath, content, 'utf-8');
